/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.tomatico.s.pizza;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *This class is intended to allow modifying the prices of pizzas.
 * @author Maiki
 */
public class CambiaPrecio extends javax.swing.JFrame {

    /**
     * Creates new form CambiaPrecio
     * @param pizzeria 
     */
    public CambiaPrecio(PizzeriaApp pizzeria) {
        initComponents();
        
        this.pizzeria = pizzeria;
        nuevoPrecioQueso.setText(String.valueOf(pizzeria.getPrecioQueso())); 
        nuevoPrecioJamon.setText(String.valueOf(pizzeria.getPrecioJamon())); 
        nuevoPrecioBandejaChica.setText(String.valueOf(pizzeria.getPrecioBandejaChica()));
        nuevoPrecioBandejaGrande.setText(String.valueOf(pizzeria.getPrecioBandejaGrande()));
        
        
    }
    
     // Método para guardar precios en un archivo
    private void guardarPrecios() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("precios.txt"))) {
            writer.write( nuevoPrecioQueso.getText() + "\n");
            writer.write( nuevoPrecioJamon.getText() + "\n");
            writer.write( nuevoPrecioBandejaChica.getText() + "\n");
            writer.write( nuevoPrecioBandejaGrande.getText() + "\n");
            JOptionPane.showMessageDialog(this, "Precios guardados correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los precios: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelCambiaPrecio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nuevoPrecioQueso = new javax.swing.JTextField();
        nuevoPrecioBandejaChica = new javax.swing.JTextField();
        nuevoPrecioJamon = new javax.swing.JTextField();
        nuevoPrecioBandejaGrande = new javax.swing.JTextField();
        aplicarBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelCambiaPrecio.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Pizza de queso");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Pizza de jamon");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Bandeja chica");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Bandeja Grande");

        nuevoPrecioQueso.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        nuevoPrecioQueso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoPrecioQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrecioQuesoActionPerformed(evt);
            }
        });

        nuevoPrecioBandejaChica.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        nuevoPrecioBandejaChica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoPrecioBandejaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrecioBandejaChicaActionPerformed(evt);
            }
        });

        nuevoPrecioJamon.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        nuevoPrecioJamon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoPrecioJamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrecioJamonActionPerformed(evt);
            }
        });

        nuevoPrecioBandejaGrande.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        nuevoPrecioBandejaGrande.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoPrecioBandejaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrecioBandejaGrandeActionPerformed(evt);
            }
        });

        aplicarBtn.setText("Aplicar");
        aplicarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCambiaPrecioLayout = new javax.swing.GroupLayout(PanelCambiaPrecio);
        PanelCambiaPrecio.setLayout(PanelCambiaPrecioLayout);
        PanelCambiaPrecioLayout.setHorizontalGroup(
            PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoPrecioQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoPrecioJamon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoPrecioBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoPrecioBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCambiaPrecioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aplicarBtn)
                .addGap(36, 36, 36))
        );
        PanelCambiaPrecioLayout.setVerticalGroup(
            PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiaPrecioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nuevoPrecioQueso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nuevoPrecioJamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nuevoPrecioBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCambiaPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(nuevoPrecioBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(aplicarBtn)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambiaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambiaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoPrecioQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrecioQuesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPrecioQuesoActionPerformed

    private void nuevoPrecioBandejaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrecioBandejaChicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPrecioBandejaChicaActionPerformed

    private void nuevoPrecioJamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrecioJamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPrecioJamonActionPerformed

    private void nuevoPrecioBandejaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrecioBandejaGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPrecioBandejaGrandeActionPerformed

    private void aplicarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarBtnActionPerformed
        
        int decision = JOptionPane.showConfirmDialog(null, "Estas seguro que deseas modificar los precios");
        
        if(decision == 0){
        pizzeria.setPrecioQueso(Integer.parseInt(nuevoPrecioQueso.getText()));
        pizzeria.setPrecioJamon(Integer.parseInt(nuevoPrecioJamon.getText()));
        pizzeria.setPrecioBandejaChica(Integer.parseInt(nuevoPrecioBandejaChica.getText()));
        pizzeria.setPrecioBandejaGrande(Integer.parseInt(nuevoPrecioBandejaGrande.getText()));
        
        guardarPrecios();
        }else{
        nuevoPrecioQueso.setText(String.valueOf(pizzeria.getPrecioQueso())); 
        nuevoPrecioJamon.setText(String.valueOf(pizzeria.getPrecioJamon())); 
        nuevoPrecioBandejaChica.setText(String.valueOf(pizzeria.getPrecioBandejaChica()));
        nuevoPrecioBandejaGrande.setText(String.valueOf(pizzeria.getPrecioBandejaGrande()));
        }
       
    }//GEN-LAST:event_aplicarBtnActionPerformed

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCambiaPrecio;
    private javax.swing.JButton aplicarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nuevoPrecioBandejaChica;
    private javax.swing.JTextField nuevoPrecioBandejaGrande;
    private javax.swing.JTextField nuevoPrecioJamon;
    private javax.swing.JTextField nuevoPrecioQueso;
    // End of variables declaration//GEN-END:variables

   private PizzeriaApp pizzeria;
}
