/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.tomatico.s.pizza;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


/**
 *This is the main class
 * @author Maiki
 */
public class PizzeriaApp extends javax.swing.JFrame {

    /**
     * Creates new form PizzeriaApp
     */
    public PizzeriaApp() {
        initComponents();
        setLocationRelativeTo(null);
        
        cargarPrecios();
        
     ingresoTotal = 0;
     ingreso = 0;
    
     
     
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPizzeria = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        pizzaQuesoLbl = new javax.swing.JLabel();
        pizzaDeJamonLbl = new javax.swing.JLabel();
        bandejaGrandeLbl = new javax.swing.JLabel();
        bandejaChicaLbl = new javax.swing.JLabel();
        cantQuesoTf = new javax.swing.JTextField();
        cantJamonTf = new javax.swing.JTextField();
        cantBandejaChicaTf = new javax.swing.JTextField();
        cantBandejaGrandeTf = new javax.swing.JTextField();
        sumJamon = new javax.swing.JLabel();
        restJamon = new javax.swing.JLabel();
        restBandejaChica = new javax.swing.JLabel();
        restQueso = new javax.swing.JLabel();
        sumBandejaChica = new javax.swing.JLabel();
        sumBandejaGrande = new javax.swing.JLabel();
        sumQueso = new javax.swing.JLabel();
        restBandejaGrande = new javax.swing.JLabel();
        totalBandejaGrande = new javax.swing.JTextField();
        totalLbl = new javax.swing.JLabel();
        cantTotal = new javax.swing.JTextField();
        totalJamon = new javax.swing.JTextField();
        totalBandejaChica = new javax.swing.JTextField();
        totalQueso = new javax.swing.JTextField();
        precios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tomatico's Pizza");
        setResizable(false);

        PanelPizzeria.setBackground(new java.awt.Color(255, 204, 153));

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzeria/tomatico/s/pizza/icons/6795cd27c8174850b3e258924fd5c3bb-free.png"))); // NOI18N

        pizzaQuesoLbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pizzaQuesoLbl.setText("Pizza de Queso");

        pizzaDeJamonLbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pizzaDeJamonLbl.setText("Pizza de jamon");

        bandejaGrandeLbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        bandejaGrandeLbl.setText("Bandeja grande de pizza queso y jamon");

        bandejaChicaLbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        bandejaChicaLbl.setText("Bandeja de pizza queso y jamon");

        cantQuesoTf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantQuesoTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantQuesoTf.setText("0");
        cantQuesoTf.setEnabled(false);
        cantQuesoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantQuesoTfActionPerformed(evt);
            }
        });

        cantJamonTf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantJamonTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantJamonTf.setText("0");
        cantJamonTf.setEnabled(false);

        cantBandejaChicaTf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantBandejaChicaTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantBandejaChicaTf.setText("0");
        cantBandejaChicaTf.setEnabled(false);
        cantBandejaChicaTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantBandejaChicaTfActionPerformed(evt);
            }
        });

        cantBandejaGrandeTf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantBandejaGrandeTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantBandejaGrandeTf.setText("0");
        cantBandejaGrandeTf.setEnabled(false);

        sumJamon.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sumJamon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumJamon.setText("+");
        sumJamon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumJamon.setOpaque(true);
        sumJamon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumJamonMouseClicked(evt);
            }
        });

        restJamon.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        restJamon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restJamon.setText("-");
        restJamon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restJamon.setOpaque(true);
        restJamon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restJamonMouseClicked(evt);
            }
        });

        restBandejaChica.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        restBandejaChica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restBandejaChica.setText("-");
        restBandejaChica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restBandejaChica.setOpaque(true);
        restBandejaChica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restBandejaChicaMouseClicked(evt);
            }
        });

        restQueso.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        restQueso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restQueso.setText("-");
        restQueso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restQueso.setOpaque(true);
        restQueso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restQuesoMouseClicked(evt);
            }
        });

        sumBandejaChica.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sumBandejaChica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumBandejaChica.setText("+");
        sumBandejaChica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumBandejaChica.setOpaque(true);
        sumBandejaChica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumBandejaChicaMouseClicked(evt);
            }
        });

        sumBandejaGrande.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sumBandejaGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumBandejaGrande.setText("+");
        sumBandejaGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumBandejaGrande.setOpaque(true);
        sumBandejaGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumBandejaGrandeMouseClicked(evt);
            }
        });

        sumQueso.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sumQueso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumQueso.setText("+");
        sumQueso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumQueso.setOpaque(true);
        sumQueso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumQuesoMouseClicked(evt);
            }
        });

        restBandejaGrande.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        restBandejaGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restBandejaGrande.setText("-");
        restBandejaGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restBandejaGrande.setOpaque(true);
        restBandejaGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restBandejaGrandeMouseClicked(evt);
            }
        });

        totalBandejaGrande.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        totalBandejaGrande.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBandejaGrande.setEnabled(false);

        totalLbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        totalLbl.setText("Total recaudado");

        cantTotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantTotal.setText("0");
        cantTotal.setEnabled(false);

        totalJamon.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        totalJamon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalJamon.setEnabled(false);

        totalBandejaChica.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        totalBandejaChica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBandejaChica.setEnabled(false);

        totalQueso.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        totalQueso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalQueso.setEnabled(false);

        precios.setText("Ajustar Precios");
        precios.setActionCommand("");
        precios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preciosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelPizzeriaLayout = new javax.swing.GroupLayout(PanelPizzeria);
        PanelPizzeria.setLayout(PanelPizzeriaLayout);
        PanelPizzeriaLayout.setHorizontalGroup(
            PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(precios)
                .addGap(30, 30, 30))
            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                        .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                        .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pizzaQuesoLbl)
                                            .addComponent(pizzaDeJamonLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                                .addComponent(sumJamon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(restJamon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cantJamonTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(totalJamon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                                .addComponent(sumQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(restQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cantQuesoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(totalQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                        .addComponent(bandejaChicaLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sumBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(restBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantBandejaChicaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                                .addComponent(bandejaGrandeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sumBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantBandejaGrandeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                        .addComponent(totalLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelPizzeriaLayout.setVerticalGroup(
            PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPizzeriaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(precios)))
                .addGap(42, 42, 42)
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantQuesoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pizzaQuesoLbl)
                    .addComponent(sumQueso)
                    .addComponent(restQueso)
                    .addComponent(totalQueso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumJamon)
                    .addComponent(restJamon)
                    .addComponent(pizzaDeJamonLbl)
                    .addComponent(cantJamonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalJamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandejaChicaLbl)
                    .addComponent(sumBandejaChica)
                    .addComponent(restBandejaChica)
                    .addComponent(cantBandejaChicaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBandejaChica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandejaGrandeLbl)
                    .addComponent(sumBandejaGrande)
                    .addComponent(restBandejaGrande)
                    .addComponent(cantBandejaGrandeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBandejaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanelPizzeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl)
                    .addComponent(cantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPizzeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPizzeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantQuesoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantQuesoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantQuesoTfActionPerformed

    private void cantBandejaChicaTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantBandejaChicaTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantBandejaChicaTfActionPerformed

    private void sumQuesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumQuesoMouseClicked
        int contador = Integer.parseInt(cantQuesoTf.getText());
        contador++;
        cantQuesoTf.setText(String.valueOf(contador));
        
        ingresoTotal +=precioQueso;
        ingreso = contador*precioQueso;
        
        totalQueso.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
    }//GEN-LAST:event_sumQuesoMouseClicked

    private void sumJamonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumJamonMouseClicked
        int contador = Integer.parseInt(cantJamonTf.getText());
        contador++;
        cantJamonTf.setText(String.valueOf(contador));
        
        ingresoTotal +=precioJamon;
        ingreso = contador*precioJamon;
        
        totalJamon.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
    }//GEN-LAST:event_sumJamonMouseClicked

    private void sumBandejaChicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumBandejaChicaMouseClicked
        int contador = Integer.parseInt(cantBandejaChicaTf.getText());
        contador++;
        cantBandejaChicaTf.setText(String.valueOf(contador));
        
        ingresoTotal +=precioBandejaChica;
        ingreso = contador*precioBandejaChica;
        
        totalBandejaChica.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
    }//GEN-LAST:event_sumBandejaChicaMouseClicked

    private void sumBandejaGrandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumBandejaGrandeMouseClicked
        int contador = Integer.parseInt(cantBandejaGrandeTf.getText());
        contador++;
        cantBandejaGrandeTf.setText(String.valueOf(contador));
        
        ingresoTotal +=precioBandejaGrande;
        ingreso = contador*precioBandejaGrande;
        
        totalBandejaGrande.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
    }//GEN-LAST:event_sumBandejaGrandeMouseClicked

    private void restQuesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restQuesoMouseClicked
        int contador = Integer.parseInt(cantQuesoTf.getText());
        
        if(contador > 0){
        contador--;
        cantQuesoTf.setText(String.valueOf(contador));
        
        ingresoTotal -=precioQueso;
        ingreso = contador*precioQueso;
        
        totalQueso.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
        }
        
    }//GEN-LAST:event_restQuesoMouseClicked

    private void restJamonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restJamonMouseClicked
       int contador = Integer.parseInt(cantJamonTf.getText());
        
        if(contador > 0){
        contador--;
        cantJamonTf.setText(String.valueOf(contador));
        
        ingresoTotal -=precioJamon;
        ingreso = contador*precioJamon;
        
        totalJamon.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
        }
    }//GEN-LAST:event_restJamonMouseClicked

    private void restBandejaChicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restBandejaChicaMouseClicked
        int contador = Integer.parseInt(cantBandejaChicaTf.getText());
        
        if(contador > 0){
        contador--;
        cantBandejaChicaTf.setText(String.valueOf(contador));
        
        ingresoTotal -=precioBandejaChica;
        ingreso = contador*precioBandejaChica;
        
        totalBandejaChica.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
        }
    }//GEN-LAST:event_restBandejaChicaMouseClicked

    private void restBandejaGrandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restBandejaGrandeMouseClicked
       int contador = Integer.parseInt(cantBandejaGrandeTf.getText());
        
        if(contador > 0){
        contador--;
        cantBandejaGrandeTf.setText(String.valueOf(contador));
        
        ingresoTotal -=precioBandejaGrande;
        ingreso = contador*precioBandejaGrande;
        
        totalBandejaGrande.setText(String.valueOf(ingreso));
        cantTotal.setText(String.valueOf(ingresoTotal));
        }
    }//GEN-LAST:event_restBandejaGrandeMouseClicked

    private void preciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preciosMouseClicked
       new CambiaPrecio(this).setVisible(true);
    }//GEN-LAST:event_preciosMouseClicked

     
    public void setPrecioQueso(int precioQueso) {
        this.precioQueso = precioQueso;
    }

    public void setPrecioJamon(int precioJamon) {
        this.precioJamon = precioJamon;
    }

    public void setPrecioBandejaChica(int precioBandejaChica) {
        this.precioBandejaChica = precioBandejaChica;
    }

    public void setPrecioBandejaGrande(int precioBandejaGrande) {
        this.precioBandejaGrande = precioBandejaGrande;
    }

    public int getPrecioQueso() {
        return precioQueso;
    }

    public int getPrecioJamon() {
        return precioJamon;
    }

    public int getPrecioBandejaChica() {
        return precioBandejaChica;
    }

    public int getPrecioBandejaGrande() {
        return precioBandejaGrande;
    }
      

    // Método para cargar los precios desde un archivo
     private void cargarPrecios() {
        try (BufferedReader reader = new BufferedReader(new FileReader("precios.txt"))) {
            precioQueso = Integer.parseInt(reader.readLine());
            precioJamon = Integer.parseInt(reader.readLine());
            precioBandejaChica = Integer.parseInt(reader.readLine());
            precioBandejaGrande = Integer.parseInt(reader.readLine());
            System.out.println("Precios cargados desde " + PRECIOS_FILE);
        } catch (IOException e) {
            System.out.println("No se pudo cargar los precios, se usarán los valores por defecto.");
        } catch (NumberFormatException e) {
            System.out.println("Error en el formato del archivo. Se usarán precios por defecto.");
        }
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new PizzeriaApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPizzeria;
    private javax.swing.JLabel bandejaChicaLbl;
    private javax.swing.JLabel bandejaGrandeLbl;
    private javax.swing.JTextField cantBandejaChicaTf;
    private javax.swing.JTextField cantBandejaGrandeTf;
    private javax.swing.JTextField cantJamonTf;
    private javax.swing.JTextField cantQuesoTf;
    private javax.swing.JTextField cantTotal;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel pizzaDeJamonLbl;
    private javax.swing.JLabel pizzaQuesoLbl;
    private javax.swing.JButton precios;
    private javax.swing.JLabel restBandejaChica;
    private javax.swing.JLabel restBandejaGrande;
    private javax.swing.JLabel restJamon;
    private javax.swing.JLabel restQueso;
    private javax.swing.JLabel sumBandejaChica;
    private javax.swing.JLabel sumBandejaGrande;
    private javax.swing.JLabel sumJamon;
    private javax.swing.JLabel sumQueso;
    private javax.swing.JTextField totalBandejaChica;
    private javax.swing.JTextField totalBandejaGrande;
    private javax.swing.JTextField totalJamon;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField totalQueso;
    // End of variables declaration//GEN-END:variables
    
    private int ingresoTotal,ingreso;
    private int precioQueso;
    private int precioJamon;
    private int precioBandejaChica;
    private int precioBandejaGrande;
    private static final String PRECIOS_FILE = "precios.txt";

}
